import { useEffect, useRef, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { ArrowLeft, ArrowRight, CheckCircle2, RotateCcw, Sparkles, X } from 'lucide-react'
import { db } from '../core/database'
import { navigate } from '../core/routing'
import { requireUnit, type Catalog } from '../core/study/catalog'
import { cardId, type ChoiceExercise, type Exercise, type ExerciseAttempt, type ExerciseSession, type TilesExercise } from '../core/study/contracts'
import { advanceExercise, discardSession, DOMAIN, groupProgress, nextGroup, startNewSession, startReviewSession, submitExerciseAnswer } from '../core/study/knowledge'
import { EmptyState, PageHeading, type PageProps } from '../components/shared'
import { UnitCard } from '../components/study/UnitCard'
import { useCatalog } from '../components/study/useCatalog'
import { HearButton, SnippetActions } from '../components/assistant/SnippetActions'
import { AnnotatedChinese } from '../components/study/AnnotatedChinese'
import { readingIndex } from '../core/study/annotate'

function useAIConnection() {
  return useLiveQuery(() => db.aiConnections.get('assistant').then(connection => connection ?? null), [])
}

export function Study({ workspace, now, run, busy }: PageProps) {
  const { catalog, error } = useCatalog()
  const connection = useAIConnection()
  const [generating, setGenerating] = useState<'new' | 'review' | ''>('')
  const known = new Set(workspace.knowledge.map(entry => entry.ref))
  const due = workspace.studyCards.filter(card => card.domain === DOMAIN && card.due <= now && known.has(card.ref)).length
  const active = workspace.exerciseSessions.filter(session => session.status === 'active').sort((a, b) => b.createdAt - a.createdAt)
  const next = catalog ? nextGroup(catalog, known) : undefined
  const progress = catalog ? groupProgress(catalog, known) : undefined
  const start = (mode: 'new' | 'review', anyway = false) => {
    setGenerating(mode)
    void run(async () => {
      try {
        const id = mode === 'new' ? await startNewSession() : await startReviewSession(Date.now(), anyway)
        navigate(`lessons/session/${id}`)
      } finally {
        setGenerating('')
      }
    })
  }
  return <>
    <PageHeading eyebrow="NEW OR REVIEW" title="Learn something new, or keep what you know.">Pick up the next items in the curriculum, or review what is due. The exercises for each session are written by your connected AI model and checked against your knowledge set.</PageHeading>
    {error && <div className="notice error" role="alert"><p>The curriculum could not be loaded. {error}</p></div>}
    {connection === null && <div className="notice" role="status"><p>Exercises are generated by your own AI connection. <a className="text-link" href="#settings">Connect a model in Settings</a> before starting a session.</p></div>}
    {generating && <div className="notice" role="status" aria-live="polite"><strong>Preparing your {generating === 'new' ? 'new items' : 'review'}...</strong><p>Your AI model is writing the exercises. This can take up to a minute.</p></div>}
    {active.length > 0 && <section className="panel"><h2>Pick up where you left off</h2><div className="resume-list">{active.map(session => <a className="resume-row" key={session.id} href={`#lessons/session/${session.id}`}>
      <div><strong>{session.mode === 'new' ? 'New items' : 'Review'}</strong><span className="small muted">Exercise {session.cursor + 1} of {session.exercises.length}</span></div><ArrowRight size={18} />
    </a>)}</div></section>}
    <div className="experience-grid two-columns">
      <section className="experience-card" aria-label="New items">
        <p className="eyebrow accent">NEW</p>
        <h2>{next ? `${next.newUnits.length} new ${next.newUnits.length === 1 ? 'item' : 'items'}` : catalog ? 'Nothing left to introduce' : 'Loading the curriculum...'}</h2>
        {next && <ul className="study-preview" lang="zh-Hans">{next.units.map(unit => <li key={unit.ref} className={known.has(unit.ref) ? 'muted' : undefined}>{unit.kind === 'vocabulary' ? unit.record.ch : unit.record.pt}</li>)}</ul>}
        {progress && <p className="small muted">HSK {next?.band ?? '6'} / group {Math.min(progress.completed + 1, progress.total)} of {progress.total}. Recently introduced items come back in each new session.</p>}
        <button className="button primary" disabled={busy || !next || !connection} onClick={() => start('new')}>Start new items <ArrowRight size={16} /></button>
      </section>
      <section className="experience-card" aria-label="Review">
        <p className="eyebrow accent">REVIEW</p>
        <h2>{due} {due === 1 ? 'item' : 'items'} due</h2>
        <p className="small muted">{workspace.knowledge.length} items in your knowledge set. Review timing follows FSRS spaced repetition for reading; an item is due when its predicted recall drops below 90%.</p>
        <div className="button-row">
          <button className="button primary" disabled={busy || !due || !connection} onClick={() => start('review')}>Review due items <ArrowRight size={16} /></button>
          {!due && workspace.knowledge.length > 0 && <button className="button secondary" disabled={busy || !connection} onClick={() => start('review', true)}>Review anyway <RotateCcw size={16} /></button>}
        </div>
      </section>
    </div>
    {!workspace.knowledge.length && <EmptyState title="Your knowledge set is empty"><p>Start with New to add the first curriculum group, or add items yourself from the Dictionary.</p><a href="#dictionary" className="button secondary">Open Dictionary</a></EmptyState>}
    <p className="page-footnote">Adding an item to your knowledge set only makes it eligible for review. Session results record practice, not proficiency or examination readiness.</p>
  </>
}

interface Annotation { readings: Map<string, Set<string>>; pinyin: boolean }

function ChoiceQuestion({ exercise, attempt, submit, busy, readings, pinyin }: Annotation & { exercise: ChoiceExercise; attempt?: ExerciseAttempt; submit: (response: unknown) => void; busy: boolean }) {
  const [selected, setSelected] = useState(attempt ? Number(attempt.response) : -1)
  const chineseQuestion = exercise.direction === 'zh-to-en'
  return <>
    {chineseQuestion
      ? <p className="practice-prompt native"><AnnotatedChinese text={exercise.question} readings={readings} pinyin={pinyin} /></p>
      : <p className="practice-prompt" lang="en">{exercise.question}</p>}
    <fieldset className="answer-options" disabled={busy || Boolean(attempt)}><legend className="visually-hidden">Choose an answer</legend>
      {exercise.options.map((option, index) => <label key={index} className={`answer-option ${selected === index ? 'selected' : ''} ${attempt && index === exercise.answer ? 'correct-option' : ''}`}>
        <input type="radio" name="answer" value={index} checked={selected === index} onChange={() => setSelected(index)} />
        {chineseQuestion ? <span lang="en">{option}</span> : <span><AnnotatedChinese text={option} readings={readings} pinyin={pinyin} /></span>}
        {!chineseQuestion && <HearButton text={option} locale="zh-Hans" label={`Hear option ${index + 1}`} iconOnly />}
        {attempt && index === exercise.answer && <CheckCircle2 size={18} aria-label="Correct answer" />}
      </label>)}
    </fieldset>
    {!attempt && <div className="button-row"><button className="button primary" disabled={busy || selected < 0} onClick={() => submit(selected)}>Check answer <CheckCircle2 size={16} /></button></div>}
  </>
}

function TilesQuestion({ exercise, attempt, submit, busy, readings, pinyin }: Annotation & { exercise: TilesExercise; attempt?: ExerciseAttempt; submit: (response: unknown) => void; busy: boolean }) {
  const all = [...exercise.tiles, ...exercise.distractors]
  const [placed, setPlaced] = useState<number[]>(() => {
    if (!attempt) return []
    const answer = JSON.parse(attempt.response) as string[]
    const used = new Set<number>()
    return answer.map(text => {
      const index = exercise.shuffled.find(candidate => !used.has(candidate) && all[candidate] === text)
      if (index !== undefined) used.add(index)
      return index ?? -1
    }).filter(index => index >= 0)
  })
  const locked = busy || Boolean(attempt)
  return <>
    <p className="practice-prompt" lang="en">{exercise.translation}</p>
    <div className="tile-answer" lang="zh-Hans" role="group" aria-label="Your sentence">
      {placed.length ? placed.map(index => <button key={index} type="button" className="tile" disabled={locked} onClick={() => setPlaced(placed.filter(item => item !== index))}><AnnotatedChinese text={all[index]} readings={readings} pinyin={pinyin} /></button>)
        : <span className="small muted">Tap the tiles in order to build the sentence.</span>}
    </div>
    <div className="tile-bank" lang="zh-Hans" role="group" aria-label="Available tiles">
      {exercise.shuffled.map(index => <button key={index} type="button" className={`tile ${placed.includes(index) ? 'tile-used' : ''}`} disabled={locked || placed.includes(index)} onClick={() => setPlaced([...placed, index])}><AnnotatedChinese text={all[index]} readings={readings} pinyin={pinyin} /></button>)}
    </div>
    {!attempt && <div className="button-row"><button className="button primary" disabled={busy || placed.length < 2} onClick={() => submit(placed.map(index => all[index]))}>Check answer <CheckCircle2 size={16} /></button></div>}
  </>
}

function SessionIntroduction({ catalog, session, workspace, run, busy, now, begin }: PageProps & { catalog: Catalog; session: ExerciseSession; begin: () => void }) {
  const group = session.groupId ? catalog.groups.get(session.groupId) : undefined
  const units = session.targetRefs.map(ref => requireUnit(catalog, ref))
  const examplesFor = (ref: string) => (group?.group.examples ?? []).filter(example => example.segments.some(segment => `vocabulary:${segment.word}` === ref) || example.grammar.some(label => `grammar:${label}` === ref))
  return <>
    <a href="#lessons" className="back-link"><ArrowLeft size={16} /> Lessons</a>
    <PageHeading eyebrow={session.mode === 'new' ? `NEW ITEMS / HSK ${units[0]?.band ?? ''}` : 'REVIEW'} title={session.mode === 'new' ? 'Meet your new items.' : 'Items in this review.'}>
      {session.mode === 'new' ? 'Read each item and its examples, then try the exercises. Items you saw in recent sessions are mixed in.' : 'These items are due according to your review schedule.'}
    </PageHeading>
    <div className="word-grid">{units.map(unit => <UnitCard key={unit.ref} catalog={catalog} unit={unit} card={workspace.studyCards.find(card => card.id === cardId(unit.ref, DOMAIN))}
      pinyin={workspace.preferences.pinyin} now={now} examples={examplesFor(unit.ref)} run={run} busy={busy} route={`lessons/session/${session.id}`} />)}</div>
    <div className="button-row"><button className="button primary" disabled={busy} onClick={begin}>Start exercises <ArrowRight size={16} /></button></div>
  </>
}

function ExercisePlayer({ catalog, session, attempt, workspace, run, busy, readings, pinyin, setPinyin }: PageProps & Annotation & {
  catalog: Catalog; session: ExerciseSession; attempt?: ExerciseAttempt; setPinyin: (value: boolean) => void
}) {
  const exercise: Exercise = session.exercises[session.cursor]
  const title = useRef<HTMLHeadingElement>(null)
  useEffect(() => { title.current?.focus() }, [])
  const submit = (response: unknown) => void run(async () => { await submitExerciseAnswer(session.id, session.cursor, response) })
  const correctSentence = exercise.type === 'tiles' ? exercise.tiles.join('') : exercise.options[exercise.answer]
  const chineseAnswer = exercise.type === 'tiles' || exercise.direction === 'en-to-zh'
  return <div className="practice-player panel" data-assistant-protected={!attempt ? 'true' : undefined}>
    <div className="card-topline"><span className="eyebrow">{session.mode === 'new' ? 'NEW ITEMS' : 'REVIEW'} / {exercise.type === 'choice' ? 'CHOOSE' : 'BUILD THE SENTENCE'}</span><span className="small muted">Exercise {session.cursor + 1} of {session.exercises.length}</span></div>
    <progress aria-label="Session progress" value={session.cursor} max={session.exercises.length} />
    <div className="practice-question-content">
      <h2 ref={title} tabIndex={-1}>{exercise.type === 'choice' ? exercise.direction === 'zh-to-en' ? 'What does this mean?' : 'Which Mandarin matches?' : 'Arrange the tiles to translate this.'}</h2>
      <p className="small muted practice-context">PRACTICES / {exercise.targets.map(ref => { const unit = requireUnit(catalog, ref); return unit.kind === 'vocabulary' ? unit.record.ch : unit.record.pt }).join(' / ')}</p>
      <div className="button-row practice-tools">
        <button type="button" className="button secondary snippet-button" aria-pressed={pinyin} onClick={() => setPinyin(!pinyin)}>{pinyin ? 'Hide pinyin' : 'Show pinyin'}</button>
        {exercise.type === 'choice' && exercise.direction === 'zh-to-en' && <HearButton text={exercise.question} locale="zh-Hans" label="Hear the Chinese" />}
      </div>
    </div>
    {exercise.type === 'choice'
      ? <ChoiceQuestion key={`${session.id}:${session.cursor}`} exercise={exercise} attempt={attempt} submit={submit} busy={busy} readings={readings} pinyin={pinyin} />
      : <TilesQuestion key={`${session.id}:${session.cursor}`} exercise={exercise} attempt={attempt} submit={submit} busy={busy} readings={readings} pinyin={pinyin} />}
    {attempt && <div className={`notice ${attempt.correct ? 'success' : ''}`} role="status">
      <strong>{attempt.correct ? 'Correct.' : 'Not quite.'}</strong>
      {chineseAnswer ? <p><AnnotatedChinese text={correctSentence} readings={readings} pinyin={pinyin} /></p> : <p lang="en">{correctSentence}</p>}
      <p className="small">{exercise.explanation}</p>
      <p className="small practice-feedback-detail">{attempt.correct ? 'Scheduled further out for each item this exercise practices.' : 'These items come back within this session window and again soon after.'}</p>
      <SnippetActions source={{ text: correctSentence, meaning: exercise.type === 'tiles' ? exercise.translation : exercise.explanation, locale: 'zh-Hans', title: 'Exercise answer explanation', route: `lessons/session/${session.id}` }} />
      <div className="button-row"><button className="button primary" disabled={busy} onClick={() => void run(() => advanceExercise(session.id, session.cursor))}>{session.cursor === session.exercises.length - 1 ? 'Finish session' : 'Next exercise'} <ArrowRight size={16} /></button></div>
    </div>}
    <p className="small muted practice-save-note">Each checked answer is saved immediately in {workspace.preferences.name}. You can leave and resume this exercise.</p>
  </div>
}

export function StudySessionPage(props: PageProps & { session: ExerciseSession }) {
  const { workspace, session, run, busy } = props
  const { catalog, error } = useCatalog()
  const [started, setStarted] = useState(false)
  const [pinyin, setPinyin] = useState(false)
  const attempts = workspace.exerciseAttempts.filter(attempt => attempt.sessionId === session.id)
  if (error) return <div className="notice error" role="alert"><p>The curriculum could not be loaded. {error}</p></div>
  if (!catalog) return <div className="opening-workspace" role="status">Loading the curriculum...</div>
  if (session.status !== 'active') {
    const correct = attempts.filter(attempt => attempt.correct).length
    return <>
      <a href="#lessons" className="back-link"><ArrowLeft size={16} /> Lessons</a>
      <PageHeading eyebrow="SMALL MOMENTS, REAL MOMENTUM" title={session.mode === 'new' ? 'New items' : 'Review'}>Read, recall, and give yourself room to learn.</PageHeading>
      <section className="panel completion">
        <CheckCircle2 size={44} className="accent" /><h2>{session.status === 'abandoned' ? 'Lesson ended early.' : 'One more step forward.'}</h2>
        <p className="completion-count">{correct} / {session.exercises.length}</p><p>correct answers</p>
        <p>You practiced {session.targetRefs.length + session.reviewRefs.length} items. Completing a session records practice, not mastery.</p>
        {session.rejected.length > 0 && <details><summary>{session.rejected.length} proposed exercises were discarded</summary><ul className="small muted">{session.rejected.map((reason, index) => <li key={index}>{reason}</li>)}</ul></details>}
        <div className="button-row"><a className="button primary" href="#lessons">Back to Lessons <ArrowRight size={16} /></a><a className="button secondary" href="#dictionary">See your knowledge set</a></div>
      </section>
    </>
  }
  const attempt = attempts.find(item => item.index === session.cursor)
  const readings = readingIndex([...new Set([...workspace.knowledge.map(entry => entry.ref), ...session.targetRefs, ...session.reviewRefs])]
    .flatMap(ref => { const unit = catalog.units.get(ref); return unit ? [unit] : [] }))
  if (session.cursor === 0 && !attempt && !started) {
    return <SessionIntroduction {...props} catalog={catalog} begin={() => setStarted(true)} />
  }
  return <>
    <div className="card-topline session-topline"><a href="#lessons" className="back-link"><ArrowLeft size={16} /> Lessons</a>
      <button className="button secondary" disabled={busy} onClick={() => void run(() => discardSession(session.id))}><X size={16} /> Quit lesson</button></div>
    <ExercisePlayer key={`${session.id}:${session.cursor}`} {...props} catalog={catalog} attempt={attempt} readings={readings} pinyin={pinyin} setPinyin={setPinyin} />
    <details className="lesson-overview"><summary><Sparkles size={16} /> Items in this session</summary>
      <div className="word-grid">{[...session.targetRefs, ...session.reviewRefs].map(ref => { const unit = requireUnit(catalog, ref); return <UnitCard key={ref} catalog={catalog} unit={unit} compact
        card={workspace.studyCards.find(card => card.id === cardId(ref, DOMAIN))} pinyin={workspace.preferences.pinyin} now={props.now} run={run} busy={busy} route={`lessons/session/${session.id}`} /> })}</div>
    </details>
  </>
}
