- {id: ko-nikl-00298-s001, level: 16, topic: society, ds: 'gender-based discrimination'}
- {id: ko-nikl-25366-s001, level: 10, topic: feelings, ds: 'dislike and hatred toward someone or something'}
- {id: ko-nikl-16283-s001, level: 10, topic: people, ds: 'quarreling or fighting'}
- {id: ko-nikl-16283-s002, level: 13, topic: leisure, ds: 'competition or contending for victory'}
- {id: ko-nikl-20383-s001, level: 15, topic: people, ds: 'friendly, close relations'}
- {id: ko-nikl-21979-s001, level: 15, topic: people, ds: 'a struggle to defeat an opponent'}
- {id: ko-nikl-21979-s002, level: 16, topic: society, ds: 'social or labor movement struggle for gains against opponents'}
- {id: ko-nikl-29822-s001, level: 15, topic: people, ds: 'living together with mutual help'}
- {id: ko-nikl-29822-s002, level: 21, topic: nature, ds: 'different kinds of organisms living together with mutual help'}
- {id: ko-nikl-51727-s001, level: 15, topic: people, ds: 'reconciliation that ends fighting and ill feeling'}
- {id: ko-nikl-22914-s001, level: 10, topic: people, ds: 'quiet harmony without worries or troubles'}
- {id: ko-nikl-03770-s002, level: 13, topic: leisure, ds: 'competition to compare performance'}
- {id: ko-nikl-03274-s001, level: 15, topic: people, ds: 'trust and loyalty'}
- {id: ko-nikl-03301-s001, level: 22, topic: reasoning, ds: 'a belief or creed one firmly upholds'}
- {id: ko-nikl-01684-s001, level: 10, topic: people, ds: 'being subjected to humiliation'}
- {id: ko-nikl-37490-s001, level: 14, topic: people, ds: 'insulting or humiliating treatment'}
- {id: ko-nikl-20531-s001, level: 8, topic: learning, ds: 'praise expressed in words, or a praising remark'}
- {id: ko-nikl-10282-s002, level: 15, topic: people, ds: 'loyalty or duties expected within relationships'}
- {id: ko-nikl-10282-s003, level: 10, topic: people, ds: 'a family-like bond without blood ties'}
- {id: ko-nikl-47338-s002, level: 8, topic: people, ds: 'connections through kinship, closeness, law, etc.'}
- {id: ko-nikl-11229-s003, level: 9, topic: reasoning, ds: 'the reason for or history behind something'}
- {id: ko-nikl-47332-s001, level: 15, topic: work, ds: 'linking or connecting things'}
- {id: ko-nikl-09302-s001, level: 15, topic: communication, ds: 'both sides of a pair or relationship'}
